Attempt to fix login with GitHub Enterprise
Since the GitHub Enterprise upgrade on 2016-01-20 to Version 2.4.3, several
users (possibly all users) are seeing an error at login time that seems to be
related to the GitHub OAuth interaction. The deploy Jenkins do not have the
same problem and are using this earlier version of the github-oauth plugin.

Here are two snippets from the stack trace that Jenkins shows to users:

java.io.IOException: {"message":"You need at least read:org scope or user scope to list your organizations.","documentation_url":"https://developer.github.com/enterprise/2.4/v3/orgs/#list-your-organizations"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:342)

and:

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://github.gds/api/v3/user/orgs
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)